[project]
name = "rolodex"
version = "0.0.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "David Brownman", email = "oss@xavd.id" }]
requires-python = ">=3.12"
dependencies = ["cyclopts ~= 4.22.5", "pydantic ~= 2.13.4"]
license-files = ["LICENSE"]
keywords = ["user-styles", "tildes", "lobsters", "css"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Utilities",
]

[project.urls]
Repository = "https://github.com/xavdid/rolodex"
Issues = "https://github.com/xavdid/rolodex/issues"
Changelog = "https://github.com/xavdid/rolodex/blob/main/CHANGELOG.md"

[project.scripts]
rolodex = "rolodex.cli:app"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = ["pytest>=9.1.1", "ruff>=0.16.3", "pyright>=1.1.409"]

[tool.ruff.lint]
extend-select = [
    "E",    # PEP8 recommendations
    "F",    # bugs
    "I001", # import sorting
    "BLE",  # catching root Exception
    "A",    # built-in shadowing
    "C4",   # unnecessary comprehensions
    "ISC",  # implicit string concat
    "PIE",  # misc useful lints
    "Q",    # better quoting behavior
    "RSE",  # no parens on exceptions that lack args
    "RET",  # more correct return behavior
    "SIM",  # general style things
    "TC",   # type-only imports should be in a typecheck block
    "ARG",  # unused args
    "PTH",  # use pathlib
    "FLY",  # short "".join calls
    "PERF", # performance hints
    "PL",   # pylint, general recommendations
]

extend-ignore = [
    "E501",    # skip enforcing line length
    "E741",    # ignore short variable names
    "PLR2004", # magic values
    "PLR0911", # too many returns
    "PLR0912", # too many branches
    "PLR0913", # too many arguments
    "PLR0915", # too many statements
    "Q000",    # single quotes; handled by formatter
    "RET503",  # requiring an explicit `return None` if that value is otherwise allowed
]

unfixable = [
    "F401", # don't remove unused imports; annoying while editing
    # run `just lint --fix --fixable F401` to fix these manually
    "F841", # don't remove unused variables
]
